### ISSUE TITLE
插件无法使用

### ISSUE THREAD

**Issue by Reversedeer** [cjladmin/nonebot_plugin_monitor#3]
作者能不能试试你的插件，pypi上的传的包有问题，pip install下载后无法使用，git clone也不行的

**Comment by lgc2333** [comment]
+1 pip发的包有问题
![image](https://user-images.githubusercontent.com/59048777/213118355-6377d276-15fd-421f-b210-9ebe3424e3b4.png)

**Comment by Reversedeer** [comment]
我这边已经解决了，不过因为风控，这个插件无法发出消息

**Comment by Reversedeer** [comment]
已经解决了，更新到我的库中
https://github.com/Reversedeer/nonebot_plugin_eventmonitor
